---
name: Super-Linter

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        uses: super-linter/super-linter@v8.3.1
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_ALL_CODEBASE: true

      - name: Set up Node.js
        # v4.4.0
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Check links in built site
        # v2.9.0
        uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8
        with:
          args: >-
            --verbose --no-progress --root-dir _site
            './_site/**/*.html' './_site/_redirects'
